# Generated by Django 4.1.6 on 2023-02-10 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblActuators',
            fields=[
                ('actuators_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('exhaust_fan', models.DecimalField(blank=True, decimal_places=0, max_digits=1, null=True)),
                ('evaporator_cooler', models.DecimalField(blank=True, decimal_places=0, max_digits=1, null=True)),
                ('greenhouse_light', models.DecimalField(blank=True, decimal_places=0, max_digits=1, null=True)),
                ('warmer_lamps', models.DecimalField(blank=True, decimal_places=0, max_digits=1, null=True)),
                ('ac_motors', models.DecimalField(blank=True, decimal_places=0, max_digits=1, null=True)),
                ('water_pump', models.DecimalField(blank=True, decimal_places=0, max_digits=1, null=True)),
                ('aeration_pump', models.DecimalField(blank=True, decimal_places=0, max_digits=1, null=True)),
                ('automatic_baiting_system', models.DecimalField(blank=True, decimal_places=0, max_digits=1, null=True)),
                ('water_heater', models.DecimalField(blank=True, decimal_places=0, max_digits=1, null=True)),
                ('water_aerator', models.DecimalField(blank=True, decimal_places=0, max_digits=1, null=True)),
                ('water_blender', models.DecimalField(blank=True, decimal_places=0, max_digits=1, null=True)),
                ('solenoid_valve_1', models.DecimalField(blank=True, decimal_places=0, max_digits=1, null=True)),
                ('solenoid_valve_2', models.DecimalField(blank=True, decimal_places=0, max_digits=1, null=True)),
                ('solenoid_valve_3', models.DecimalField(blank=True, decimal_places=0, max_digits=1, null=True)),
                ('solenoid_valve_4', models.DecimalField(blank=True, decimal_places=0, max_digits=1, null=True)),
            ],
            options={
                'db_table': 'tbl_actuators',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblFishData',
            fields=[
                ('fd_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('fish_width', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fish_height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fish_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'tbl_fish_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblGreenhouse',
            fields=[
                ('greenhouse_id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'tbl_greenhouse',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblGreenhouseMonitoring',
            fields=[
                ('gm_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('air_temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('relative_humidity', models.IntegerField(blank=True, null=True)),
                ('co2_level', models.IntegerField(blank=True, null=True)),
                ('intensity_illumination', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'tbl_greenhouse_monitoring',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblPlantData',
            fields=[
                ('pd_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('plant_health', models.DecimalField(blank=True, decimal_places=0, max_digits=1, null=True)),
            ],
            options={
                'db_table': 'tbl_plant_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblUserData',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=25, null=True)),
                ('password', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_user_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblWaterBiofilter',
            fields=[
                ('wbf_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('nitrite', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('nitrate', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('ammonia', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
            ],
            options={
                'db_table': 'tbl_water_biofilter',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblWaterSensingtank',
            fields=[
                ('wst_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('ph_level', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('water_temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('elec_conductivity', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('total_dissolved_solids', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'tbl_water_sensingtank',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblWaterTestbed',
            fields=[
                ('wtb_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('ph_level', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('water_temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dissolved_o2_level', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('elec_conductivity', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('total_dissolved_solids', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('nitrite', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('nitrate', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('ammonia', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
            ],
            options={
                'db_table': 'tbl_water_testbed',
                'managed': False,
            },
        ),
    ]
